<a href="https://colab.research.google.com/github/jrami12/codepath-prework/blob/main/JanetRamirezHW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier, export_graphviz # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn import tree

In [4]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

df = pd.read_csv (r'/content/gdrive/MyDrive/Colab Notebooks/adviseinvest.csv')

Mounted at /content/gdrive

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
#look at the top rows
df.head(10)

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
0,1,13520,0,23,0,1,1,0,0.0,0,2,0,1,2
1,0,14780,0,22,2,1,0,1,0.0,3,0,3,0,0
2,1,37570,0,62,2,1,0,0,1.0,3,0,4,0,4
3,0,12450,0,33,2,1,0,1,0.0,1,0,2,0,0
4,0,12400,0,48,1,2,0,0,1.0,2,1,4,0,0
5,1,14030,0,28,2,1,1,0,1.0,0,0,2,0,4
6,1,9320,0,24,2,1,0,1,0.0,3,0,2,0,2
7,1,11750,0,68,0,1,0,0,1.0,1,0,0,0,3
8,1,69670,0,36,3,1,1,0,0.0,1,1,3,0,4
9,1,3380,0,52,2,1,0,1,0.0,0,2,4,0,4

In [7]:
#look at the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29504 entries, 0 to 29503
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   answered        29504 non-null  int64
 1   income          29504 non-null  int64
 2   female          29504 non-null  int64
 3   age             29504 non-null  int64
 4   job             29504 non-null  int64
 5   num_dependents  29504 non-null  int64
 6   rent            29504 non-null  int64
 7   own_res         29504 non-null  int64
 8   new_car         29502 non-null  float64
 9   chk_acct        29504 non-null  int64
 10  sav_acct        29504 non-null  int64
 11  num_accts       29504 non-null  int64
 12  mobile          29504 non-null  int64
 13  product         29504 non-null  int64
dtypes: float64(1), int64(13)
memory usage: 3.2 MB

In [8]:
#describe the data before cleaning it
df.describe()

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
count,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29502.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000
mean,0.546638,33766.893303,0.054230,34.770065,1.915401,1.140998,0.210412,0.681128,0.240797,1.468547,0.956616,2.458175,0.091106,1.535792
std,0.497829,29379.202710,0.226475,11.355777,0.658183,0.348025,0.407608,0.466047,0.427575,1.234727,1.483946,19.497353,0.287765,1.625916
min,0.000000,-65600.000000,0.000000,19.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,13550.000000,0.000000,26.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
50%,1.000000,23310.000000,0.000000,32.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,1.000000
75%,1.000000,41690.000000,0.000000,40.000000,2.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,3.000000
max,1.000000,159450.000000,1.000000,74.000000,3.000000,2.000000,1.000000,1.000000,1.000000,3.000000,4.000000,3345.000000,1.000000,4.000000

In [9]:
#Cleaning data
df = df.dropna()
df = df[df['num_accts'] < 5]
df = df[df['income'] >= 0]
df[['job', 'product', 'chk_acct', 'sav_acct']] = df[['job', 'product', 'chk_acct', 'sav_acct']].astype('category')
df.describe()

,answered,income,female,age,num_dependents,rent,own_res,new_car,num_accts,mobile
count,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000
mean,0.546595,33772.499407,0.054171,34.768840,1.141022,0.210448,0.681074,0.240788,2.344859,0.091088
std,0.497833,29374.485379,0.226359,11.354486,0.348050,0.407634,0.466068,0.427569,1.200390,0.287739
min,0.000000,2760.000000,0.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,13550.000000,0.000000,26.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000
50%,1.000000,23310.000000,0.000000,32.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000
75%,1.000000,41690.000000,0.000000,40.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.000000
max,1.000000,159450.000000,1.000000,74.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [10]:
mean_answered = df['answered'].mean()
print("Mean of 'answered':", mean_answered)
df.describe()
print(df.dtypes)

Mean of 'answered': 0.5465947998237228
answered             int64
income               int64
female               int64
age                  int64
job               category
num_dependents       int64
rent                 int64
own_res              int64
new_car            float64
chk_acct          category
sav_acct          category
num_accts            int64
mobile               int64
product           category
dtype: object